name: Publish Docker
on:
  push:
    branches:
      - master
      jobs:
        build:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@master
            - name: Publish to Registry
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                name: chanok9417/bdbb-server 
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                dockerfile: Dockerfile
                snapshot: true
            - name: Discord notification
              env:
                DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              uses: Ilshidur/action-discord@master
              with:
                args: '{{ EVENT_PAYLOAD.repository.full_name }} 프로젝트가 배포되었습니다.'