name: Publish Docker (Dev)
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: chanok9417/bdbb-server 
          username: chanok9417
          password: joung0406
          dockerfile: Dockerfile
          tag_names: true
